name: Chimera CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=services --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: false

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy
    
    - name: Run Ruff
      run: ruff check . --output-format=github
    
    - name: Check formatting (Black)
      run: black --check .
    
    - name: Type checking (MyPy)
      run: mypy services/ --ignore-missing-imports || true

  spec-check:
    name: Specification Alignment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Verify specs exist
      run: |
        echo "Checking for required specification files..."
        test -f specs/_meta.md || (echo "Missing specs/_meta.md" && exit 1)
        test -f specs/functional.md || (echo "Missing specs/functional.md" && exit 1)
        test -f specs/technical.md || (echo "Missing specs/technical.md" && exit 1)
        echo "✓ All required specs present"
    
    - name: Verify skills structure
      run: |
        echo "Checking skills directory structure..."
        test -d skills/ || (echo "Missing skills/ directory" && exit 1)
        test -f skills/README.md || (echo "Missing skills/README.md" && exit 1)
        echo "✓ Skills structure valid"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy security scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t chimera:${{ github.sha }} .
        docker build -t chimera:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm chimera:${{ github.sha }} python -c "import sys; print(f'Python {sys.version}')"
    
    - name: Save Docker image
      run: docker save chimera:latest | gzip > chimera-latest.tar.gz
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: chimera-latest.tar.gz

  # Optional: AI Code Review with CodeRabbit
  # Uncomment when CodeRabbit is configured
  # ai-review:
  #   name: AI Code Review
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   
  #   steps:
  #   - name: CodeRabbit Review
  #     uses: coderabbitai/coderabbit-action@v1
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       check_spec_alignment: true
  #       check_security: true
